apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-cluster
  region: us-east-1

nodeGroups:
  - name: mlmodel-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      publicKeyPath: ~/.ssh/udacity.pem
  - name: mlmodel-2
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/udacity.pem