apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-091515c3f995480c6 }
      us-east-1b: { id: subnet-08d0bdc7b5b855433 }
      us-east-1c: { id: subnet-0acb0160cb166e5e0 }
      us-east-1d: { id: subnet-005a098ab40b987e2 }
      us-east-1e: { id: subnet-06c9cbfb8ad6e46e2 }
      us-east-1f: { id: subnet-0b7ef4d8039294811 }

nodeGroups:
  - name: mlmodel-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      publickey: udacity
  - name: mlmodel-2
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 100
