apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-cluster
  region: us-east-1a,us-east-1b,us-east-1c

nodeGroups:
  - name: mlmodel-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      publickey: udacity
  - name: mlmodel-2
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 100
