apiVersion: v1
kind: Service
metadata:
  name: mlmodel-app-service
  labels:
    name: mlmodel-app
spec:
  selector:
    app: mlmodel-app
  ports:
    - name: http
      port: 8000
      targetPort: 80
  type: LoadBalancer